name: CI

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Please select a release type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
  pull_request:

jobs:
  print-context:
    name: Print GitHub Context Values
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print GitHub Context
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "github.base_ref: ${{ github.base_ref }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.event_name: ${{ github.event_name }}"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
